### ISSUE TITLE
[BUG] NoClassDefFoundError with 1.16.2 and SmallAdditions v1.4.9

### ISSUE THREAD

**Issue by TheLonelyWolf1** [pablo3x6/SmallAdditions#6]
**Describe the bug**
The Plugin can't load on 1.16.2-Servers, because the entity-class can't be found. (Tested with Paper and Spigot)

**To Reproduce**
1. Use Spigot or Paper with Minecraft 1.16.2
2. Start the Server with SmallAdditions v1.4.9
3. Error on Startup

**Expected behavior**
Plugin should find the class and start as normal.

**Spigot/Bukkit/Paper (please complete the following information):**
 - Spigot 1.16.2
 - Paper 1.16.2 (Build #147 and #146)

**Additional context**
Error:

> [12:06:03] [Server thread/ERROR]: Error occurred while enabling SmallAdditions v1.4.9 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_16_R1/Entity
	at si.zbe.smalladd.Main.registerEvents(Main.java:86) ~[?:?]
	at si.zbe.smalladd.Main.onEnable(Main.java:25) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-147]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-147]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-147]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-147]
	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-147]
	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.2.jar:git-Paper-147]
	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.2.jar:git-Paper-147]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-147]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-147]
	at net.minecraft.server.v1_16_R2.MinecraftServer$$Lambda$3249/1563320404.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R1.Entity
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:105) ~[patched_1.16.2.jar:git-Paper-147]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.2.jar:git-Paper-147]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 13 more

**Comment by TheLonelyWolf1** [comment]
I looked through the code and worked on it a little bit. 
Changing **"v1_16_R1"** to  **"v1_16_R2"** should fix this problem.

**Comment by zbejas** [comment]
Will post a fix soon, got to find some time to sit down and work on it.

**Comment by TheLonelyWolf1** [comment]
As far as i've seen, import-references to **v1_16_R1** are made in:

- TitleManager.java
- CropEvent.java
- TotemDeathEvent.java

Hope, this helps

**Comment by zbejas** [comment]
I just need to rebuild the plugin with newer corebukkit and spigot versions, however, I do not find the time. I will probably rebuild it by the end of the year.

**Comment by jafuuu** [comment]
> 
> 
> I just need to rebuild the plugin with newer corebukkit and spigot versions, however, I do not find the time. I will probably rebuild it by the end of the year.

any updates?

**Comment by Sputnik1996** [comment]
I hope this man is going well, this is an ABOLUTELY MUST-TO-HAVE WONDERFUL PLUGIN.
I really hope he finds the time to come back.

GODSWORK!!!

**Comment by zbejas** [comment]
The dependencies are now updated to 1.16.5. Since I haven't tested any of the functions, I will not be uploading the plugin to SpigotMC right now. You can either compile it yourself for now or DM me to test this version and improve it together.

If you find any issues, just open up another issue. Im sorry for all the time it took.

**Comment by Snaider1** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSS

LET'S GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

THANK YOU SO MUUUUUUUUUUUUCH!!!!!!!!
