### ISSUE TITLE
[BUG] SmallAdditions 1.4.9.1 can't be loaded on Spigot 1.16.5

### ISSUE THREAD

**Issue by Sputnik1996** [pablo3x6/SmallAdditions#8]
**Describe the bug**
The plugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**To Reproduce**

1. Use Spigot with Minecraft 1.16.5
2. Start the Server with SmallAdditions v1.4.9.1
3. Can't load the plugin

**Spigot/Bukkit/Paper (please complete the following information):**
 - Spigot 1.16.5

**Additional context**
[20:35:25] [Server thread/ERROR]: Could not load 'plugins\SmallAdditions-1.4.9.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: si/zbe/smalladd/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.UnsupportedClassVersionError: si/zbe/smalladd/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_281]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:2991-Spigot-018b9a0-f3f3094]
        ... 7 more

**Comment by zbejas** [comment]
Update java to 11, or compile the plugin in java 8. I was using java 11 when compiling this version.

**Comment by Sputnik1996** [comment]
Thank you! and excuse my ignorance, I'm going to test the plugin right now <3
